aws:
  dynamodb:
    #endpoint: https://ap-south-1.console.aws.amazon.com/   # Replace <your-region> with your AWS region (e.g., us-east-1)
    endpoint: https://dynamodb.ap-south-1.amazonaws.com   # Replace <your-region> with your AWS region (e.g., us-east-1)
    region: ap-south-1                                   # Replace <your-region> with your AWS region
    accessKeyId: AKIAYSE4N4EW7PEZUOGY                       # Your AWS access key ID
    secretAccessKey: XpqyINKc9cPw7lhIS9N/9pvxWAhrLt9sJvvHIVLP               # Your AWS secret access key

spring:
  application:
    name: productservice

#aws:
#  dynamodb:
#    endpoint: https://dynamodb.<your-region>.amazonaws.com   # Replace <your-region> with your AWS region (e.g., us-east-1)
#    region: <your-region>                                   # Replace <your-region> with your AWS region
#    accessKeyId: <your-access-key-id>                       # Your AWS access key ID
#    secretAccessKey: <your-secret-access-key>               # Your AWS secret access key
#
